


slides:
	R CMD Sweave slides.Rnw
	pdflatex slides.tex
	pdflatex slides.tex
	make clean


clean:
	-rm slides-*.pdf
	-rm slides.aux
	-rm slides.log
	-rm slides.nav
	-rm slides.out
	-rm slides.snm
	-rm slides.tex
	-rm slides.toc
	-rm slides.vrb
