#' HCL-based discrete qualitative color scales for ggplot2
#'
#' Discrete ggplot2 color scales using the color palettes generated by \code{\link{qualitative_hcl}}. 
#'
#' 
#' If both a valid palette name and palette parameters are provided then the provided palette parameters overwrite the parameters in the
#' named palette. This enables easy customization of named palettes.
#' 
#' @param c. Chroma value in the HCL color description.
#' @param l Luminance value in the HCL color description.
#' @param h1	The hue at which the rainbow begins.
#' @param h2 The hue at which the rainbow ends.
#' @param alpha Numeric vector of values in the range \code{[0, 1]} for alpha transparency channel (0 means transparent and 1 means opaque).
#' @param palette The name of the palette to be used. Run \code{hcl_palettes(type = "qual")} for available options.
#' @param nmax Maximum number of different colors the palette should contain. If not provided, is calculated automatically
#'  from the data.
#' @param order Numeric vector listing the order in which the colors should be used. Default is \code{1:nmax}.
#' @param ... common discrete scale parameters: \code{name}, \code{breaks}, \code{labels}, \code{na.value}, \code{limits} and \code{guide}. See
#'  \code{\link{discrete_scale}} for more details.
#' @examples
#' library(ggplot2)
#' 
#' # default colors
#' ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) +
#'   geom_point() + scale_color_discrete_qualitative()
#'  
#' # color scale "Harmonic"
#' ggplot(iris, aes(Sepal.Length, fill = Species)) +
#'   geom_density(alpha = 0.7) + scale_fill_discrete_qualitative(palette = "Harmonic")
#' @export
scale_colour_discrete_qualitative <- function(palette = "Harmonic", c. = NULL, l = NULL, h1 = NULL, h2 = NULL,
                                   alpha = 1, nmax = NULL, order = NULL, ...)
{
  hcl_args <- c("c.", "l", "h1", "h2", "palette", alpha) # arguments we want to hand off to function qualitative_hcl
  
  # match hcl_args to args provided
  args <- as.list(match.call())
  args[[1]] <- NULL # remove the function call
  args <- args[na.omit(match(hcl_args, names(args)))] # remove other args
  
  pal <- function(n) {
    if (is.null(nmax)) nmax <- n
    if (is.null(order)) order <- 1:n
    
    if (n > nmax) {
      warning("Insufficient values in scale_colour_discrete_qualitative. ", n, " needed but only ",
              nmax, " provided.", call. = FALSE)
    }
    # set the n argument and call qualitative_hcl
    args <- c(args, list(n = nmax))
    do.call(qualitative_hcl, args)[order]
  }
  ggplot2::discrete_scale("colour", "manual", pal, ...)
}

#' @rdname scale_colour_discrete_qualitative
#' @export
scale_color_discrete_qualitative <- scale_colour_discrete_qualitative

#' @rdname scale_colour_discrete_qualitative
#' @export
scale_fill_discrete_qualitative <- function(palette = "Harmonic", c. = NULL, l = NULL, h1 = NULL, h2 = NULL,
                                            alpha = 1, nmax = NULL, order = NULL, ...)
{
  hcl_args <- c("c.", "l", "h1", "h2", "palette", alpha) # arguments we want to hand off to function qualitative_hcl
  
  # match hcl_args to args provided
  args <- as.list(match.call())
  args[[1]] <- NULL # remove the function call
  args <- args[na.omit(match(hcl_args, names(args)))] # remove other args
  
  pal <- function(n) {
    if (is.null(nmax)) nmax <- n
    if (is.null(order)) order <- 1:n
    
    if (n > nmax) {
      warning("Insufficient values in scale_fill_discrete_qualitative. ", n, " needed but only ",
              nmax, " provided.", call. = FALSE)
    }
    # set the n argument and call qualitative_hcl
    args <- c(args, list(n = nmax))
    do.call(qualitative_hcl, args)[order]
  }
  ggplot2::discrete_scale("fill", "manual", pal, ...)
}
